server:
  port: 8090

spring:
  datasource:
    name: dataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/myblog?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  username: root
  password: root


## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winter.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
